{ config, lib, pkgs, modulesPath, ... }:

# Generated by `nixos-generate-config` on the dev-desktop libvirt VM
# (2026-06-12). Regenerate with:
#   sudo nixos-generate-config --root /mnt --dir /tmp/cfg
#   cp /tmp/cfg/hardware-configuration.nix hosts/hardware/dev-desktop.nix
# Bootloader config lives in ../dev-desktop.nix (the host file), not here —
# `nixos-generate-config` does not emit boot.loader settings, so keeping
# them here would mean losing them on every regeneration.

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d864fd04-5390-4523-a753-2a4860b6f0e0";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
