{ config, lib, pkgs, modulesPath, ... }:

# Generated by `nixos-generate-config` on the openclaw Proxmox VM
# (2026-09-14). Regenerate with:
#   sudo nixos-generate-config --root /mnt --dir /tmp/cfg
#   cp /tmp/cfg/hardware-configuration.nix hosts/hardware/openclaw.nix
# Bootloader config lives in ../openclaw.nix (the host file), not here —
# `nixos-generate-config` does not emit boot.loader settings, so keeping
# them here would mean losing them on every regeneration.

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9396672c-47da-4bc0-875e-6e7f2d6b4136";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
